import type { RoleConfig, UserRole } from './access.types';

export const ROLE_CONFIG: Record<UserRole, RoleConfig> = {
  shoouts: {
    id: 'shoouts',
    label: 'Shoouts',
    description: 'Free listener and buyer marketplace experience.',
    isPaid: false,
    defaultExperience: 'shoouts',
    availableExperiences: ['shoouts'],
    previewExperiences: ['vault', 'studio', 'hybrid'],
    permissions: [
      'marketplace.view',
      'marketplace.stream',
      'marketplace.cart',
      'marketplace.buy',
      'marketplace.download',
      'vault.preview',
      'studio.preview',
      'chat.buyer',
    ],
    limits: {
      vaultStorageGb: 0,
      vaultMaxUploads: 0,
      vaultMaxFileSizeMb: 0,
      studioMaxListings: 0,
    },
    upgradeTarget: 'vault',
  },

  vault: {
    id: 'vault',
    label: 'Vault',
    description: 'Private creator workspace with free storage limits.',
    isPaid: false,
    defaultExperience: 'vault',
    availableExperiences: ['shoouts', 'vault'],
    previewExperiences: ['studio', 'hybrid'],
    permissions: [
      'marketplace.view',
      'marketplace.stream',
      'marketplace.cart',
      'marketplace.buy',
      'marketplace.download',
      'vault.preview',
      'vault.view',
      'vault.upload',
      'vault.record',
      'vault.folders',
      'vault.privatePlayback',
      'vault.sharePreviewLinks',
      'vault.upgradeStorage',
      'studio.preview',
      'chat.buyer',
    ],
    limits: {
      vaultStorageGb: 0.05,
      vaultMaxUploads: 50,
      vaultMaxFileSizeMb: 100,
      studioMaxListings: 0,
    },
    upgradeTarget: 'vault_pro',
  },

  vault_pro: {
    id: 'vault_pro',
    label: 'Vault Pro',
    description: 'Higher-storage private workspace for creators.',
    isPaid: true,
    defaultExperience: 'vault',
    availableExperiences: ['shoouts', 'vault'],
    previewExperiences: ['studio', 'hybrid'],
    permissions: [
      'marketplace.view',
      'marketplace.stream',
      'marketplace.cart',
      'marketplace.buy',
      'marketplace.download',
      'vault.preview',
      'vault.view',
      'vault.upload',
      'vault.record',
      'vault.folders',
      'vault.privatePlayback',
      'vault.sharePreviewLinks',
      'vault.upgradeStorage',
      'studio.preview',
      'chat.buyer',
    ],
    limits: {
      vaultStorageGb: 5,
      vaultMaxUploads: 500,
      vaultMaxFileSizeMb: 300,
      studioMaxListings: 0,
    },
    upgradeTarget: 'hybrid',
  },

  studio: {
    id: 'studio',
    label: 'Studio',
    description: 'Paid seller workspace for publishing, promotion, and payouts.',
    isPaid: true,
    defaultExperience: 'studio',
    availableExperiences: ['shoouts', 'studio'],
    previewExperiences: ['vault', 'hybrid'],
    permissions: [
      'marketplace.view',
      'marketplace.stream',
      'marketplace.cart',
      'marketplace.buy',
      'marketplace.download',
      'studio.preview',
      'studio.view',
      'studio.upload',
      'studio.publish',
      'studio.promote',
      'studio.analyticsBasic',
      'studio.payouts',
      'studio.kyc',
      'chat.buyer',
      'chat.seller',
    ],
    limits: {
      vaultStorageGb: 0,
      vaultMaxUploads: 0,
      vaultMaxFileSizeMb: 0,
      studioMaxListings: 'unlimited',
    },
    upgradeTarget: 'hybrid',
  },

  hybrid: {
    id: 'hybrid',
    label: 'Hybrid',
    description: 'Complete creator workflow: Vault plus Studio in one dashboard.',
    isPaid: true,
    defaultExperience: 'hybrid',
    availableExperiences: ['shoouts', 'vault', 'studio', 'hybrid'],
    previewExperiences: [],
    permissions: [
      'marketplace.view',
      'marketplace.stream',
      'marketplace.cart',
      'marketplace.buy',
      'marketplace.download',

      'vault.preview',
      'vault.view',
      'vault.upload',
      'vault.record',
      'vault.folders',
      'vault.privatePlayback',
      'vault.sharePreviewLinks',
      'vault.upgradeStorage',

      'studio.preview',
      'studio.view',
      'studio.upload',
      'studio.publish',
      'studio.promote',
      'studio.analyticsBasic',
      'studio.payouts',
      'studio.kyc',

      'hybrid.view',
      'hybrid.publishFromVault',

      'chat.buyer',
      'chat.seller',
    ],
    limits: {
      vaultStorageGb: 10,
      vaultMaxUploads: 1000,
      vaultMaxFileSizeMb: 500,
      studioMaxListings: 'unlimited',
    },
    upgradeTarget: null,
  },
};